/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.pluggedin.ffmpeg;

public enum AVAudioServiceType {
  AV_AUDIO_SERVICE_TYPE_MAIN(0),
  AV_AUDIO_SERVICE_TYPE_EFFECTS(1),
  AV_AUDIO_SERVICE_TYPE_VISUALLY_IMPAIRED(2),
  AV_AUDIO_SERVICE_TYPE_HEARING_IMPAIRED(3),
  AV_AUDIO_SERVICE_TYPE_DIALOGUE(4),
  AV_AUDIO_SERVICE_TYPE_COMMENTARY(5),
  AV_AUDIO_SERVICE_TYPE_EMERGENCY(6),
  AV_AUDIO_SERVICE_TYPE_VOICE_OVER(7),
  AV_AUDIO_SERVICE_TYPE_KARAOKE(8),
  AV_AUDIO_SERVICE_TYPE_NB;

  public final int swigValue() {
    return swigValue;
  }

  public static AVAudioServiceType swigToEnum(int swigValue) {
    AVAudioServiceType[] swigValues = AVAudioServiceType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (AVAudioServiceType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + AVAudioServiceType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private AVAudioServiceType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private AVAudioServiceType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private AVAudioServiceType(AVAudioServiceType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

