/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.pluggedin.ffmpeg;

public class AVBitStreamFilterContext {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AVBitStreamFilterContext(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AVBitStreamFilterContext obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ffmpegJNI.delete_AVBitStreamFilterContext(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPriv_data(SWIGTYPE_p_void value) {
    ffmpegJNI.AVBitStreamFilterContext_priv_data_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getPriv_data() {
    long cPtr = ffmpegJNI.AVBitStreamFilterContext_priv_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setFilter(AVBitStreamFilter value) {
    ffmpegJNI.AVBitStreamFilterContext_filter_set(swigCPtr, this, AVBitStreamFilter.getCPtr(value), value);
  }

  public AVBitStreamFilter getFilter() {
    long cPtr = ffmpegJNI.AVBitStreamFilterContext_filter_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AVBitStreamFilter(cPtr, false);
  }

  public void setParser(AVCodecParserContext value) {
    ffmpegJNI.AVBitStreamFilterContext_parser_set(swigCPtr, this, AVCodecParserContext.getCPtr(value), value);
  }

  public AVCodecParserContext getParser() {
    long cPtr = ffmpegJNI.AVBitStreamFilterContext_parser_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AVCodecParserContext(cPtr, false);
  }

  public void setNext(AVBitStreamFilterContext value) {
    ffmpegJNI.AVBitStreamFilterContext_next_set(swigCPtr, this, AVBitStreamFilterContext.getCPtr(value), value);
  }

  public AVBitStreamFilterContext getNext() {
    long cPtr = ffmpegJNI.AVBitStreamFilterContext_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AVBitStreamFilterContext(cPtr, false);
  }

  public AVBitStreamFilterContext() {
    this(ffmpegJNI.new_AVBitStreamFilterContext(), true);
  }

}
