/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.pluggedin.ffmpeg;

public class AVChapter {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AVChapter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AVChapter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ffmpegJNI.delete_AVChapter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(int value) {
    ffmpegJNI.AVChapter_id_set(swigCPtr, this, value);
  }

  public int getId() {
    return ffmpegJNI.AVChapter_id_get(swigCPtr, this);
  }

  public void setTime_base(SWIGTYPE_p_AVRational value) {
    ffmpegJNI.AVChapter_time_base_set(swigCPtr, this, SWIGTYPE_p_AVRational.getCPtr(value));
  }

  public SWIGTYPE_p_AVRational getTime_base() {
    return new SWIGTYPE_p_AVRational(ffmpegJNI.AVChapter_time_base_get(swigCPtr, this), true);
  }

  public void setStart(SWIGTYPE_p_int64_t value) {
    ffmpegJNI.AVChapter_start_set(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int64_t getStart() {
    return new SWIGTYPE_p_int64_t(ffmpegJNI.AVChapter_start_get(swigCPtr, this), true);
  }

  public void setEnd(SWIGTYPE_p_int64_t value) {
    ffmpegJNI.AVChapter_end_set(swigCPtr, this, SWIGTYPE_p_int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_int64_t getEnd() {
    return new SWIGTYPE_p_int64_t(ffmpegJNI.AVChapter_end_get(swigCPtr, this), true);
  }

  public void setMetadata(SWIGTYPE_p_AVDictionary value) {
    ffmpegJNI.AVChapter_metadata_set(swigCPtr, this, SWIGTYPE_p_AVDictionary.getCPtr(value));
  }

  public SWIGTYPE_p_AVDictionary getMetadata() {
    long cPtr = ffmpegJNI.AVChapter_metadata_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_AVDictionary(cPtr, false);
  }

  public AVChapter() {
    this(ffmpegJNI.new_AVChapter(), true);
  }

}
