/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.pluggedin.ffmpeg;

public enum AVChromaLocation {
  AVCHROMA_LOC_UNSPECIFIED(0),
  AVCHROMA_LOC_LEFT(1),
  AVCHROMA_LOC_CENTER(2),
  AVCHROMA_LOC_TOPLEFT(3),
  AVCHROMA_LOC_TOP(4),
  AVCHROMA_LOC_BOTTOMLEFT(5),
  AVCHROMA_LOC_BOTTOM(6),
  AVCHROMA_LOC_NB;

  public final int swigValue() {
    return swigValue;
  }

  public static AVChromaLocation swigToEnum(int swigValue) {
    AVChromaLocation[] swigValues = AVChromaLocation.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (AVChromaLocation swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + AVChromaLocation.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private AVChromaLocation() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private AVChromaLocation(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private AVChromaLocation(AVChromaLocation swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

