/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.pluggedin.ffmpeg;

public enum AVClassCategory {
  AV_CLASS_CATEGORY_NA(0),
  AV_CLASS_CATEGORY_INPUT,
  AV_CLASS_CATEGORY_OUTPUT,
  AV_CLASS_CATEGORY_MUXER,
  AV_CLASS_CATEGORY_DEMUXER,
  AV_CLASS_CATEGORY_ENCODER,
  AV_CLASS_CATEGORY_DECODER,
  AV_CLASS_CATEGORY_FILTER,
  AV_CLASS_CATEGORY_BITSTREAM_FILTER,
  AV_CLASS_CATEGORY_SWSCALER,
  AV_CLASS_CATEGORY_SWRESAMPLER,
  AV_CLASS_CATEGORY_NB;

  public final int swigValue() {
    return swigValue;
  }

  public static AVClassCategory swigToEnum(int swigValue) {
    AVClassCategory[] swigValues = AVClassCategory.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (AVClassCategory swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + AVClassCategory.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private AVClassCategory() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private AVClassCategory(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private AVClassCategory(AVClassCategory swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

