/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.pluggedin.ffmpeg;

public enum AVColorTransferCharacteristic {
  AVCOL_TRC_BT709(1),
  AVCOL_TRC_UNSPECIFIED(2),
  AVCOL_TRC_GAMMA22(4),
  AVCOL_TRC_GAMMA28(5),
  AVCOL_TRC_SMPTE240M(7),
  AVCOL_TRC_NB;

  public final int swigValue() {
    return swigValue;
  }

  public static AVColorTransferCharacteristic swigToEnum(int swigValue) {
    AVColorTransferCharacteristic[] swigValues = AVColorTransferCharacteristic.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (AVColorTransferCharacteristic swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + AVColorTransferCharacteristic.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private AVColorTransferCharacteristic() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private AVColorTransferCharacteristic(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private AVColorTransferCharacteristic(AVColorTransferCharacteristic swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

