/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.pluggedin.ffmpeg;

public enum AVColorPrimaries {
  AVCOL_PRI_BT709(1),
  AVCOL_PRI_UNSPECIFIED(2),
  AVCOL_PRI_BT470M(4),
  AVCOL_PRI_BT470BG(5),
  AVCOL_PRI_SMPTE170M(6),
  AVCOL_PRI_SMPTE240M(7),
  AVCOL_PRI_FILM(8),
  AVCOL_PRI_NB;

  public final int swigValue() {
    return swigValue;
  }

  public static AVColorPrimaries swigToEnum(int swigValue) {
    AVColorPrimaries[] swigValues = AVColorPrimaries.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (AVColorPrimaries swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + AVColorPrimaries.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private AVColorPrimaries() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private AVColorPrimaries(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private AVColorPrimaries(AVColorPrimaries swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

