/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.pluggedin.ffmpeg;

public class AVCodecParser {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AVCodecParser(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AVCodecParser obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ffmpegJNI.delete_AVCodecParser(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCodec_ids(SWIGTYPE_p_int value) {
    ffmpegJNI.AVCodecParser_codec_ids_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getCodec_ids() {
    long cPtr = ffmpegJNI.AVCodecParser_codec_ids_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setPriv_data_size(int value) {
    ffmpegJNI.AVCodecParser_priv_data_size_set(swigCPtr, this, value);
  }

  public int getPriv_data_size() {
    return ffmpegJNI.AVCodecParser_priv_data_size_get(swigCPtr, this);
  }

  public void setParser_init(SWIGTYPE_p_f_p_struct_AVCodecParserContext__int value) {
    ffmpegJNI.AVCodecParser_parser_init_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_AVCodecParserContext__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_AVCodecParserContext__int getParser_init() {
    long cPtr = ffmpegJNI.AVCodecParser_parser_init_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_AVCodecParserContext__int(cPtr, false);
  }

  public void setParser_parse(SWIGTYPE_p_f_p_struct_AVCodecParserContext_p_struct_AVCodecContext_p_p_q_const__unsigned_char_p_int_p_q_const__unsigned_char_int__int value) {
    ffmpegJNI.AVCodecParser_parser_parse_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_AVCodecParserContext_p_struct_AVCodecContext_p_p_q_const__unsigned_char_p_int_p_q_const__unsigned_char_int__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_AVCodecParserContext_p_struct_AVCodecContext_p_p_q_const__unsigned_char_p_int_p_q_const__unsigned_char_int__int getParser_parse() {
    long cPtr = ffmpegJNI.AVCodecParser_parser_parse_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_AVCodecParserContext_p_struct_AVCodecContext_p_p_q_const__unsigned_char_p_int_p_q_const__unsigned_char_int__int(cPtr, false);
  }

  public void setParser_close(SWIGTYPE_p_f_p_struct_AVCodecParserContext__void value) {
    ffmpegJNI.AVCodecParser_parser_close_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_AVCodecParserContext__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_AVCodecParserContext__void getParser_close() {
    long cPtr = ffmpegJNI.AVCodecParser_parser_close_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_AVCodecParserContext__void(cPtr, false);
  }

  public void setSplit(SWIGTYPE_p_f_p_struct_AVCodecContext_p_q_const__unsigned_char_int__int value) {
    ffmpegJNI.AVCodecParser_split_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_AVCodecContext_p_q_const__unsigned_char_int__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_AVCodecContext_p_q_const__unsigned_char_int__int getSplit() {
    long cPtr = ffmpegJNI.AVCodecParser_split_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_AVCodecContext_p_q_const__unsigned_char_int__int(cPtr, false);
  }

  public void setNext(AVCodecParser value) {
    ffmpegJNI.AVCodecParser_next_set(swigCPtr, this, AVCodecParser.getCPtr(value), value);
  }

  public AVCodecParser getNext() {
    long cPtr = ffmpegJNI.AVCodecParser_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AVCodecParser(cPtr, false);
  }

  public AVCodecParser() {
    this(ffmpegJNI.new_AVCodecParser(), true);
  }

}
