/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.pluggedin.ffmpeg;

public class AVDictionary {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AVDictionary(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AVDictionary obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ffmpegJNI.delete_AVDictionary(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCount(int value) {
    ffmpegJNI.AVDictionary_count_set(swigCPtr, this, value);
  }

  public int getCount() {
    return ffmpegJNI.AVDictionary_count_get(swigCPtr, this);
  }

  public void setElems(SWIGTYPE_p_AVDictionaryEntry value) {
    ffmpegJNI.AVDictionary_elems_set(swigCPtr, this, SWIGTYPE_p_AVDictionaryEntry.getCPtr(value));
  }

  public SWIGTYPE_p_AVDictionaryEntry getElems() {
    long cPtr = ffmpegJNI.AVDictionary_elems_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_AVDictionaryEntry(cPtr, false);
  }

  public AVDictionary() {
    this(ffmpegJNI.new_AVDictionary(), true);
  }

}
