/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.pluggedin.ffmpeg;

public enum AVDiscard {
  AVDISCARD_NONE(-16),
  AVDISCARD_DEFAULT(0),
  AVDISCARD_NONREF(8),
  AVDISCARD_BIDIR(16),
  AVDISCARD_NONKEY(32),
  AVDISCARD_ALL(48);

  public final int swigValue() {
    return swigValue;
  }

  public static AVDiscard swigToEnum(int swigValue) {
    AVDiscard[] swigValues = AVDiscard.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (AVDiscard swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + AVDiscard.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private AVDiscard() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private AVDiscard(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private AVDiscard(AVDiscard swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

