/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.pluggedin.ffmpeg;

public enum AVDurationEstimationMethod {
  AVFMT_DURATION_FROM_PTS,
  AVFMT_DURATION_FROM_STREAM,
  AVFMT_DURATION_FROM_BITRATE;

  public final int swigValue() {
    return swigValue;
  }

  public static AVDurationEstimationMethod swigToEnum(int swigValue) {
    AVDurationEstimationMethod[] swigValues = AVDurationEstimationMethod.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (AVDurationEstimationMethod swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + AVDurationEstimationMethod.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private AVDurationEstimationMethod() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private AVDurationEstimationMethod(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private AVDurationEstimationMethod(AVDurationEstimationMethod swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

