/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.pluggedin.ffmpeg;

public class AVFilterFormats {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AVFilterFormats(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AVFilterFormats obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ffmpegJNI.delete_AVFilterFormats(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFormat_count(long value) {
    ffmpegJNI.AVFilterFormats_format_count_set(swigCPtr, this, value);
  }

  public long getFormat_count() {
    return ffmpegJNI.AVFilterFormats_format_count_get(swigCPtr, this);
  }

  public void setFormats(SWIGTYPE_p_int value) {
    ffmpegJNI.AVFilterFormats_formats_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getFormats() {
    long cPtr = ffmpegJNI.AVFilterFormats_formats_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setRefcount(long value) {
    ffmpegJNI.AVFilterFormats_refcount_set(swigCPtr, this, value);
  }

  public long getRefcount() {
    return ffmpegJNI.AVFilterFormats_refcount_get(swigCPtr, this);
  }

  public void setRefs(SWIGTYPE_p_p_p_AVFilterFormats value) {
    ffmpegJNI.AVFilterFormats_refs_set(swigCPtr, this, SWIGTYPE_p_p_p_AVFilterFormats.getCPtr(value));
  }

  public SWIGTYPE_p_p_p_AVFilterFormats getRefs() {
    long cPtr = ffmpegJNI.AVFilterFormats_refs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_p_AVFilterFormats(cPtr, false);
  }

  public AVFilterFormats() {
    this(ffmpegJNI.new_AVFilterFormats(), true);
  }

}
