/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.pluggedin.ffmpeg;

public class AVIndexEntry {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AVIndexEntry(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AVIndexEntry obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ffmpegJNI.delete_AVIndexEntry(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPos(long value) {
    ffmpegJNI.AVIndexEntry_pos_set(swigCPtr, this, value);
  }

  public long getPos() {
    return ffmpegJNI.AVIndexEntry_pos_get(swigCPtr, this);
  }

  public void setTimestamp(long value) {
    ffmpegJNI.AVIndexEntry_timestamp_set(swigCPtr, this, value);
  }

  public long getTimestamp() {
    return ffmpegJNI.AVIndexEntry_timestamp_get(swigCPtr, this);
  }

  public void setFlags(int value) {
    ffmpegJNI.AVIndexEntry_flags_set(swigCPtr, this, value);
  }

  public int getFlags() {
    return ffmpegJNI.AVIndexEntry_flags_get(swigCPtr, this);
  }

  public void setSize(int value) {
    ffmpegJNI.AVIndexEntry_size_set(swigCPtr, this, value);
  }

  public int getSize() {
    return ffmpegJNI.AVIndexEntry_size_get(swigCPtr, this);
  }

  public void setMin_distance(int value) {
    ffmpegJNI.AVIndexEntry_min_distance_set(swigCPtr, this, value);
  }

  public int getMin_distance() {
    return ffmpegJNI.AVIndexEntry_min_distance_get(swigCPtr, this);
  }

  public AVIndexEntry() {
    this(ffmpegJNI.new_AVIndexEntry(), true);
  }

}
