/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.pluggedin.ffmpeg;

public class AVInputFormat {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AVInputFormat(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AVInputFormat obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ffmpegJNI.delete_AVInputFormat(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setName(byte[] value) {
    ffmpegJNI.AVInputFormat_name_set(swigCPtr, this, value);
  }

  public byte[] getName() {
    return ffmpegJNI.AVInputFormat_name_get(swigCPtr, this);
  }

  public void setLong_name(byte[] value) {
    ffmpegJNI.AVInputFormat_long_name_set(swigCPtr, this, value);
  }

  public byte[] getLong_name() {
    return ffmpegJNI.AVInputFormat_long_name_get(swigCPtr, this);
  }

  public void setPriv_data_size(int value) {
    ffmpegJNI.AVInputFormat_priv_data_size_set(swigCPtr, this, value);
  }

  public int getPriv_data_size() {
    return ffmpegJNI.AVInputFormat_priv_data_size_get(swigCPtr, this);
  }

  public void setRead_probe(SWIGTYPE_p_f_p_struct_AVProbeData__int value) {
    ffmpegJNI.AVInputFormat_read_probe_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_AVProbeData__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_AVProbeData__int getRead_probe() {
    long cPtr = ffmpegJNI.AVInputFormat_read_probe_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_AVProbeData__int(cPtr, false);
  }

  public void setRead_header(SWIGTYPE_p_f_p_struct_AVFormatContext_p_struct_AVFormatParameters__int value) {
    ffmpegJNI.AVInputFormat_read_header_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_AVFormatContext_p_struct_AVFormatParameters__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_AVFormatContext_p_struct_AVFormatParameters__int getRead_header() {
    long cPtr = ffmpegJNI.AVInputFormat_read_header_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_AVFormatContext_p_struct_AVFormatParameters__int(cPtr, false);
  }

  public void setRead_packet(SWIGTYPE_p_f_p_struct_AVFormatContext_p_struct_AVPacket__int value) {
    ffmpegJNI.AVInputFormat_read_packet_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_AVFormatContext_p_struct_AVPacket__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_AVFormatContext_p_struct_AVPacket__int getRead_packet() {
    long cPtr = ffmpegJNI.AVInputFormat_read_packet_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_AVFormatContext_p_struct_AVPacket__int(cPtr, false);
  }

  public void setRead_close(SWIGTYPE_p_f_p_struct_AVFormatContext__int value) {
    ffmpegJNI.AVInputFormat_read_close_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_AVFormatContext__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_AVFormatContext__int getRead_close() {
    long cPtr = ffmpegJNI.AVInputFormat_read_close_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_AVFormatContext__int(cPtr, false);
  }

  public void setRead_timestamp(SWIGTYPE_p_f_p_struct_AVFormatContext_int_p_int64_t_int64_t__int64_t value) {
    ffmpegJNI.AVInputFormat_read_timestamp_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_AVFormatContext_int_p_int64_t_int64_t__int64_t.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_AVFormatContext_int_p_int64_t_int64_t__int64_t getRead_timestamp() {
    long cPtr = ffmpegJNI.AVInputFormat_read_timestamp_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_AVFormatContext_int_p_int64_t_int64_t__int64_t(cPtr, false);
  }

  public void setFlags(int value) {
    ffmpegJNI.AVInputFormat_flags_set(swigCPtr, this, value);
  }

  public int getFlags() {
    return ffmpegJNI.AVInputFormat_flags_get(swigCPtr, this);
  }

  public void setExtensions(byte[] value) {
    ffmpegJNI.AVInputFormat_extensions_set(swigCPtr, this, value);
  }

  public byte[] getExtensions() {
    return ffmpegJNI.AVInputFormat_extensions_get(swigCPtr, this);
  }

  public void setValue(int value) {
    ffmpegJNI.AVInputFormat_value_set(swigCPtr, this, value);
  }

  public int getValue() {
    return ffmpegJNI.AVInputFormat_value_get(swigCPtr, this);
  }

  public void setRead_play(SWIGTYPE_p_f_p_struct_AVFormatContext__int value) {
    ffmpegJNI.AVInputFormat_read_play_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_AVFormatContext__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_AVFormatContext__int getRead_play() {
    long cPtr = ffmpegJNI.AVInputFormat_read_play_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_AVFormatContext__int(cPtr, false);
  }

  public void setRead_pause(SWIGTYPE_p_f_p_struct_AVFormatContext__int value) {
    ffmpegJNI.AVInputFormat_read_pause_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_AVFormatContext__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_AVFormatContext__int getRead_pause() {
    long cPtr = ffmpegJNI.AVInputFormat_read_pause_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_AVFormatContext__int(cPtr, false);
  }

  public void setCodec_tag(SWIGTYPE_p_p_AVCodecTag value) {
    ffmpegJNI.AVInputFormat_codec_tag_set(swigCPtr, this, SWIGTYPE_p_p_AVCodecTag.getCPtr(value));
  }

  public SWIGTYPE_p_p_AVCodecTag getCodec_tag() {
    long cPtr = ffmpegJNI.AVInputFormat_codec_tag_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_AVCodecTag(cPtr, false);
  }

  public void setRead_seek2(SWIGTYPE_p_f_p_struct_AVFormatContext_int_int64_t_int64_t_int64_t_int__int value) {
    ffmpegJNI.AVInputFormat_read_seek2_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_AVFormatContext_int_int64_t_int64_t_int64_t_int__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_AVFormatContext_int_int64_t_int64_t_int64_t_int__int getRead_seek2() {
    long cPtr = ffmpegJNI.AVInputFormat_read_seek2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_AVFormatContext_int_int64_t_int64_t_int64_t_int__int(cPtr, false);
  }

  public void setPriv_class(SWIGTYPE_p_AVClass value) {
    ffmpegJNI.AVInputFormat_priv_class_set(swigCPtr, this, SWIGTYPE_p_AVClass.getCPtr(value));
  }

  public SWIGTYPE_p_AVClass getPriv_class() {
    long cPtr = ffmpegJNI.AVInputFormat_priv_class_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_AVClass(cPtr, false);
  }

  public void setNext(AVInputFormat value) {
    ffmpegJNI.AVInputFormat_next_set(swigCPtr, this, AVInputFormat.getCPtr(value), value);
  }

  public AVInputFormat getNext() {
    long cPtr = ffmpegJNI.AVInputFormat_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AVInputFormat(cPtr, false);
  }

  public AVInputFormat() {
    this(ffmpegJNI.new_AVInputFormat(), true);
  }

}
