/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.pluggedin.ffmpeg;

public class AVOption_default_val {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AVOption_default_val(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AVOption_default_val obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ffmpegJNI.delete_AVOption_default_val(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDbl(double value) {
    ffmpegJNI.AVOption_default_val_dbl_set(swigCPtr, this, value);
  }

  public double getDbl() {
    return ffmpegJNI.AVOption_default_val_dbl_get(swigCPtr, this);
  }

  public void setStr(String value) {
    ffmpegJNI.AVOption_default_val_str_set(swigCPtr, this, value);
  }

  public String getStr() {
    return ffmpegJNI.AVOption_default_val_str_get(swigCPtr, this);
  }

  public void setI64(long value) {
    ffmpegJNI.AVOption_default_val_i64_set(swigCPtr, this, value);
  }

  public long getI64() {
    return ffmpegJNI.AVOption_default_val_i64_get(swigCPtr, this);
  }

  public void setQ(AVRational value) {
    ffmpegJNI.AVOption_default_val_q_set(swigCPtr, this, AVRational.getCPtr(value), value);
  }

  public AVRational getQ() {
    long cPtr = ffmpegJNI.AVOption_default_val_q_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AVRational(cPtr, false);
  }

  public AVOption_default_val() {
    this(ffmpegJNI.new_AVOption_default_val(), true);
  }

}
