/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.pluggedin.ffmpeg;

public class AVPacketList {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AVPacketList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AVPacketList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ffmpegJNI.delete_AVPacketList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPkt(AVPacket value) {
    ffmpegJNI.AVPacketList_pkt_set(swigCPtr, this, AVPacket.getCPtr(value), value);
  }

  public AVPacket getPkt() {
    long cPtr = ffmpegJNI.AVPacketList_pkt_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AVPacket(cPtr, false);
  }

  public void setNext(AVPacketList value) {
    ffmpegJNI.AVPacketList_next_set(swigCPtr, this, AVPacketList.getCPtr(value), value);
  }

  public AVPacketList getNext() {
    long cPtr = ffmpegJNI.AVPacketList_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AVPacketList(cPtr, false);
  }

  public AVPacketList() {
    this(ffmpegJNI.new_AVPacketList(), true);
  }

}
