/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.pluggedin.ffmpeg;

public class AVPacket_side_data {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AVPacket_side_data(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AVPacket_side_data obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ffmpegJNI.delete_AVPacket_side_data(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setData(SWIGTYPE_p_uint8_t value) {
    ffmpegJNI.AVPacket_side_data_data_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getData() {
    long cPtr = ffmpegJNI.AVPacket_side_data_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_uint8_t(cPtr, false);
  }

  public void setSize(int value) {
    ffmpegJNI.AVPacket_side_data_size_set(swigCPtr, this, value);
  }

  public int getSize() {
    return ffmpegJNI.AVPacket_side_data_size_get(swigCPtr, this);
  }

  public void setType(AVPacketSideDataType value) {
    ffmpegJNI.AVPacket_side_data_type_set(swigCPtr, this, value.swigValue());
  }

  public AVPacketSideDataType getType() {
    return AVPacketSideDataType.swigToEnum(ffmpegJNI.AVPacket_side_data_type_get(swigCPtr, this));
  }

  public AVPacket_side_data() {
    this(ffmpegJNI.new_AVPacket_side_data(), true);
  }

}
