/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.pluggedin.ffmpeg;

public enum AVPacketSideDataType {
  AV_PKT_DATA_PALETTE;

  public final int swigValue() {
    return swigValue;
  }

  public static AVPacketSideDataType swigToEnum(int swigValue) {
    AVPacketSideDataType[] swigValues = AVPacketSideDataType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (AVPacketSideDataType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + AVPacketSideDataType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private AVPacketSideDataType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private AVPacketSideDataType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private AVPacketSideDataType(AVPacketSideDataType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

