/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.pluggedin.ffmpeg;

public class AVPanScan {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AVPanScan(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AVPanScan obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ffmpegJNI.delete_AVPanScan(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(int value) {
    ffmpegJNI.AVPanScan_id_set(swigCPtr, this, value);
  }

  public int getId() {
    return ffmpegJNI.AVPanScan_id_get(swigCPtr, this);
  }

  public void setWidth(int value) {
    ffmpegJNI.AVPanScan_width_set(swigCPtr, this, value);
  }

  public int getWidth() {
    return ffmpegJNI.AVPanScan_width_get(swigCPtr, this);
  }

  public void setHeight(int value) {
    ffmpegJNI.AVPanScan_height_set(swigCPtr, this, value);
  }

  public int getHeight() {
    return ffmpegJNI.AVPanScan_height_get(swigCPtr, this);
  }

  public void setPosition(SWIGTYPE_p_a_2__short value) {
    ffmpegJNI.AVPanScan_position_set(swigCPtr, this, SWIGTYPE_p_a_2__short.getCPtr(value));
  }

  public SWIGTYPE_p_a_2__short getPosition() {
    long cPtr = ffmpegJNI.AVPanScan_position_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_2__short(cPtr, false);
  }

  public AVPanScan() {
    this(ffmpegJNI.new_AVPanScan(), true);
  }

}
