/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.pluggedin.ffmpeg;

public enum AVPictureType {
  AV_PICTURE_TYPE_NONE(0),
  AV_PICTURE_TYPE_I,
  AV_PICTURE_TYPE_P,
  AV_PICTURE_TYPE_B,
  AV_PICTURE_TYPE_S,
  AV_PICTURE_TYPE_SI,
  AV_PICTURE_TYPE_SP,
  AV_PICTURE_TYPE_BI;

  public final int swigValue() {
    return swigValue;
  }

  public static AVPictureType swigToEnum(int swigValue) {
    AVPictureType[] swigValues = AVPictureType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (AVPictureType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + AVPictureType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private AVPictureType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private AVPictureType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private AVPictureType(AVPictureType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

