/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.pluggedin.ffmpeg;

public class AVProbeData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AVProbeData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AVProbeData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ffmpegJNI.delete_AVProbeData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFilename(byte[] value) {
    ffmpegJNI.AVProbeData_filename_set(swigCPtr, this, value);
  }

  public byte[] getFilename() {
    return ffmpegJNI.AVProbeData_filename_get(swigCPtr, this);
  }

  public void setBuf(SWIGTYPE_p_unsigned_char value) {
    ffmpegJNI.AVProbeData_buf_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getBuf() {
    long cPtr = ffmpegJNI.AVProbeData_buf_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setBuf_size(int value) {
    ffmpegJNI.AVProbeData_buf_size_set(swigCPtr, this, value);
  }

  public int getBuf_size() {
    return ffmpegJNI.AVProbeData_buf_size_get(swigCPtr, this);
  }

  public AVProbeData() {
    this(ffmpegJNI.new_AVProbeData(), true);
  }

}
