/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.pluggedin.ffmpeg;

public class AVRational {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AVRational(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AVRational obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ffmpegJNI.delete_AVRational(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNum(int value) {
    ffmpegJNI.AVRational_num_set(swigCPtr, this, value);
  }

  public int getNum() {
    return ffmpegJNI.AVRational_num_get(swigCPtr, this);
  }

  public void setDen(int value) {
    ffmpegJNI.AVRational_den_set(swigCPtr, this, value);
  }

  public int getDen() {
    return ffmpegJNI.AVRational_den_get(swigCPtr, this);
  }

  public AVRational() {
    this(ffmpegJNI.new_AVRational(), true);
  }

}
