/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.pluggedin.ffmpeg;

public enum AVRounding {
  AV_ROUND_ZERO(0),
  AV_ROUND_INF(1),
  AV_ROUND_DOWN(2),
  AV_ROUND_UP(3),
  AV_ROUND_NEAR_INF(5);

  public final int swigValue() {
    return swigValue;
  }

  public static AVRounding swigToEnum(int swigValue) {
    AVRounding[] swigValues = AVRounding.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (AVRounding swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + AVRounding.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private AVRounding() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private AVRounding(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private AVRounding(AVRounding swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

