/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.pluggedin.ffmpeg;

public enum AVSubtitleType {
  SUBTITLE_NONE,
  SUBTITLE_BITMAP,
  SUBTITLE_TEXT,
  SUBTITLE_ASS;

  public final int swigValue() {
    return swigValue;
  }

  public static AVSubtitleType swigToEnum(int swigValue) {
    AVSubtitleType[] swigValues = AVSubtitleType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (AVSubtitleType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + AVSubtitleType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private AVSubtitleType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private AVSubtitleType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private AVSubtitleType(AVSubtitleType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

