/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.pluggedin.ffmpeg;

public class char_array_1d {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected char_array_1d(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(char_array_1d obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ffmpegJNI.delete_char_array_1d(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public char_array_1d(int nelements) {
    this(ffmpegJNI.new_char_array_1d(nelements), true);
  }

  public short getitem(int index) {
    return ffmpegJNI.char_array_1d_getitem(swigCPtr, this, index);
  }

  public void setitem(int index, short value) {
    ffmpegJNI.char_array_1d_setitem(swigCPtr, this, index, value);
  }

  public SWIGTYPE_p_unsigned_char cast() {
    long cPtr = ffmpegJNI.char_array_1d_cast(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public static char_array_1d frompointer(SWIGTYPE_p_unsigned_char t) {
    long cPtr = ffmpegJNI.char_array_1d_frompointer(SWIGTYPE_p_unsigned_char.getCPtr(t));
    return (cPtr == 0) ? null : new char_array_1d(cPtr, false);
  }

}
