/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.pluggedin.ffmpeg;

public class DecodeResult {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DecodeResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DecodeResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ffmpegJNI.delete_DecodeResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setReturnCode(int value) {
    ffmpegJNI.DecodeResult_returnCode_set(swigCPtr, this, value);
  }

  public int getReturnCode() {
    return ffmpegJNI.DecodeResult_returnCode_get(swigCPtr, this);
  }

  public void setGotPicture(int value) {
    ffmpegJNI.DecodeResult_gotPicture_set(swigCPtr, this, value);
  }

  public int getGotPicture() {
    return ffmpegJNI.DecodeResult_gotPicture_get(swigCPtr, this);
  }

  public DecodeResult() {
    this(ffmpegJNI.new_DecodeResult(), true);
  }

}
