/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.pluggedin.ffmpeg;

public enum Motion_Est_ID {
  ME_ZERO(1),
  ME_FULL,
  ME_LOG,
  ME_PHODS,
  ME_EPZS,
  ME_X1,
  ME_HEX,
  ME_UMH,
  ME_ITER,
  ME_TESA;

  public final int swigValue() {
    return swigValue;
  }

  public static Motion_Est_ID swigToEnum(int swigValue) {
    Motion_Est_ID[] swigValues = Motion_Est_ID.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (Motion_Est_ID swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + Motion_Est_ID.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private Motion_Est_ID() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private Motion_Est_ID(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private Motion_Est_ID(Motion_Est_ID swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

