/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.pluggedin.ffmpeg;

public enum PixelFormat {
  PIX_FMT_NONE(-1),
  PIX_FMT_YUV420P,
  PIX_FMT_YUYV422,
  PIX_FMT_RGB24,
  PIX_FMT_BGR24,
  PIX_FMT_YUV422P,
  PIX_FMT_YUV444P,
  PIX_FMT_YUV410P,
  PIX_FMT_YUV411P,
  PIX_FMT_GRAY8,
  PIX_FMT_MONOWHITE,
  PIX_FMT_MONOBLACK,
  PIX_FMT_PAL8,
  PIX_FMT_YUVJ420P,
  PIX_FMT_YUVJ422P,
  PIX_FMT_YUVJ444P,
  PIX_FMT_XVMC_MPEG2_MC,
  PIX_FMT_XVMC_MPEG2_IDCT,
  PIX_FMT_UYVY422,
  PIX_FMT_UYYVYY411,
  PIX_FMT_BGR8,
  PIX_FMT_BGR4,
  PIX_FMT_BGR4_BYTE,
  PIX_FMT_RGB8,
  PIX_FMT_RGB4,
  PIX_FMT_RGB4_BYTE,
  PIX_FMT_NV12,
  PIX_FMT_NV21,
  PIX_FMT_ARGB,
  PIX_FMT_RGBA,
  PIX_FMT_ABGR,
  PIX_FMT_BGRA,
  PIX_FMT_GRAY16BE,
  PIX_FMT_GRAY16LE,
  PIX_FMT_YUV440P,
  PIX_FMT_YUVJ440P,
  PIX_FMT_YUVA420P,
  PIX_FMT_VDPAU_H264,
  PIX_FMT_VDPAU_MPEG1,
  PIX_FMT_VDPAU_MPEG2,
  PIX_FMT_VDPAU_WMV3,
  PIX_FMT_VDPAU_VC1,
  PIX_FMT_RGB48BE,
  PIX_FMT_RGB48LE,
  PIX_FMT_RGB565BE,
  PIX_FMT_RGB565LE,
  PIX_FMT_RGB555BE,
  PIX_FMT_RGB555LE,
  PIX_FMT_BGR565BE,
  PIX_FMT_BGR565LE,
  PIX_FMT_BGR555BE,
  PIX_FMT_BGR555LE,
  PIX_FMT_VAAPI_MOCO,
  PIX_FMT_VAAPI_IDCT,
  PIX_FMT_VAAPI_VLD,
  PIX_FMT_YUV420P16LE,
  PIX_FMT_YUV420P16BE,
  PIX_FMT_YUV422P16LE,
  PIX_FMT_YUV422P16BE,
  PIX_FMT_YUV444P16LE,
  PIX_FMT_YUV444P16BE,
  PIX_FMT_VDPAU_MPEG4,
  PIX_FMT_DXVA2_VLD,
  PIX_FMT_RGB444LE,
  PIX_FMT_RGB444BE,
  PIX_FMT_BGR444LE,
  PIX_FMT_BGR444BE,
  PIX_FMT_GRAY8A,
  PIX_FMT_BGR48BE,
  PIX_FMT_BGR48LE,
  PIX_FMT_YUV420P9BE,
  PIX_FMT_YUV420P9LE,
  PIX_FMT_YUV420P10BE,
  PIX_FMT_YUV420P10LE,
  PIX_FMT_YUV422P10BE,
  PIX_FMT_YUV422P10LE,
  PIX_FMT_YUV444P9BE,
  PIX_FMT_YUV444P9LE,
  PIX_FMT_YUV444P10BE,
  PIX_FMT_YUV444P10LE,
  PIX_FMT_YUV422P9BE,
  PIX_FMT_YUV422P9LE,
  PIX_FMT_VDA_VLD,
  PIX_FMT_GBRP,
  PIX_FMT_GBRP9BE,
  PIX_FMT_GBRP9LE,
  PIX_FMT_GBRP10BE,
  PIX_FMT_GBRP10LE,
  PIX_FMT_GBRP16BE,
  PIX_FMT_GBRP16LE,
  PIX_FMT_RGBA64BE(0x123),
  PIX_FMT_RGBA64LE,
  PIX_FMT_BGRA64BE,
  PIX_FMT_BGRA64LE,
  PIX_FMT_0RGB(0x123+4),
  PIX_FMT_RGB0,
  PIX_FMT_0BGR,
  PIX_FMT_BGR0,
  PIX_FMT_NB;

  public final int swigValue() {
    return swigValue;
  }

  public static PixelFormat swigToEnum(int swigValue) {
    PixelFormat[] swigValues = PixelFormat.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (PixelFormat swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + PixelFormat.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private PixelFormat() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private PixelFormat(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private PixelFormat(PixelFormat swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

