/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.pluggedin.ffmpeg;

public class SWIGTYPE_p_AVRational {
  private long swigCPtr;

  protected SWIGTYPE_p_AVRational(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_AVRational() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_AVRational obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

