/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.pluggedin.ffmpeg;

public enum SwrDitherType {
  SWR_DITHER_NONE(0),
  SWR_DITHER_RECTANGULAR,
  SWR_DITHER_TRIANGULAR,
  SWR_DITHER_TRIANGULAR_HIGHPASS,
  SWR_DITHER_NB;

  public final int swigValue() {
    return swigValue;
  }

  public static SwrDitherType swigToEnum(int swigValue) {
    SwrDitherType[] swigValues = SwrDitherType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (SwrDitherType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + SwrDitherType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private SwrDitherType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private SwrDitherType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private SwrDitherType(SwrDitherType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

