/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.pluggedin.ffmpeg;

public enum SwrFilterType {
  SWR_FILTER_TYPE_CUBIC,
  SWR_FILTER_TYPE_BLACKMAN_NUTTALL,
  SWR_FILTER_TYPE_KAISER;

  public final int swigValue() {
    return swigValue;
  }

  public static SwrFilterType swigToEnum(int swigValue) {
    SwrFilterType[] swigValues = SwrFilterType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (SwrFilterType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + SwrFilterType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private SwrFilterType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private SwrFilterType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private SwrFilterType(SwrFilterType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

