/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pluggedin_dsp_AECJNI */

#ifndef _Included_com_pluggedin_dsp_AECJNI
#define _Included_com_pluggedin_dsp_AECJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pluggedin_dsp_AECJNI
 * Method:    create
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_pluggedin_dsp_AECJNI_create
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_pluggedin_dsp_AECJNI
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_pluggedin_dsp_AECJNI_destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_pluggedin_dsp_AECJNI
 * Method:    echo_cancel
 * Signature: (J[S[S)[S
 */
JNIEXPORT jshortArray JNICALL Java_com_pluggedin_dsp_AECJNI_echo_1cancel
  (JNIEnv *, jclass, jlong, jshortArray, jshortArray);

/*
 * Class:     com_pluggedin_dsp_AECJNI
 * Method:    echo_playback
 * Signature: (J[S)V
 */
JNIEXPORT void JNICALL Java_com_pluggedin_dsp_AECJNI_echo_1playback
  (JNIEnv *, jclass, jlong, jshortArray);

/*
 * Class:     com_pluggedin_dsp_AECJNI
 * Method:    echo_capture
 * Signature: (J[S)[S
 */
JNIEXPORT jshortArray JNICALL Java_com_pluggedin_dsp_AECJNI_echo_1capture
  (JNIEnv *, jclass, jlong, jshortArray);

#ifdef __cplusplus
}
#endif
#endif
