/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pluggedin_dsp_FFTJNI */

#ifndef _Included_com_pluggedin_dsp_FFTJNI
#define _Included_com_pluggedin_dsp_FFTJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pluggedin_dsp_FFTJNI
 * Method:    create
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_pluggedin_dsp_FFTJNI_create
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_pluggedin_dsp_FFTJNI
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_pluggedin_dsp_FFTJNI_destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_pluggedin_dsp_FFTJNI
 * Method:    fwd
 * Signature: (J[D[D)I
 */
JNIEXPORT jint JNICALL Java_com_pluggedin_dsp_FFTJNI_fwd
  (JNIEnv *, jclass, jlong, jdoubleArray, jdoubleArray);

/*
 * Class:     com_pluggedin_dsp_FFTJNI
 * Method:    inv
 * Signature: (J[D[D)I
 */
JNIEXPORT jint JNICALL Java_com_pluggedin_dsp_FFTJNI_inv
  (JNIEnv *, jclass, jlong, jdoubleArray, jdoubleArray);

/*
 * Class:     com_pluggedin_dsp_FFTJNI
 * Method:    fwd_r2c
 * Signature: (J[D[D)I
 */
JNIEXPORT jint JNICALL Java_com_pluggedin_dsp_FFTJNI_fwd_1r2c
  (JNIEnv *, jclass, jlong, jdoubleArray, jdoubleArray);

/*
 * Class:     com_pluggedin_dsp_FFTJNI
 * Method:    inv_c2r
 * Signature: (J[D[D)I
 */
JNIEXPORT jint JNICALL Java_com_pluggedin_dsp_FFTJNI_inv_1c2r
  (JNIEnv *, jclass, jlong, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
